/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.table.planner.plan.`trait`

import org.apache.calcite.plan.{RelOptPlanner, RelTrait, RelTraitDef}
import org.apache.flink.table.dataformat.RowKind
import org.apache.calcite.rel.RelNode

/**
 * A marker tells the [[RelNode]] itself needs to emit [[RowKind.UPDATE_BEFORE]] messages if
 * it emit update messages. If this node needs to emit update before, the update before message
 * is either generated by this node or generated by upstreams and forwarded by this node.
 */
class SendBeforeImageForUpdatesTrait(val sendBeforeImageForUpdates: Boolean) extends RelTrait {

  override def getTraitDef: RelTraitDef[_ <: RelTrait] = SendBeforeImageForUpdatesTraitDef.INSTANCE

  override def satisfies(`trait`: RelTrait): Boolean = this.equals(`trait`)

  override def register(planner: RelOptPlanner): Unit = {}

  override def hashCode(): Int = sendBeforeImageForUpdates.hashCode()

  override def equals(obj: Any): Boolean = obj match {
    case t: SendBeforeImageForUpdatesTrait =>
      this.sendBeforeImageForUpdates.equals(t.sendBeforeImageForUpdates)
    case _ => false
  }

  override def toString: String = sendBeforeImageForUpdates.toString
}

object SendBeforeImageForUpdatesTrait {
  def apply(emitUpdateBefore: Boolean): SendBeforeImageForUpdatesTrait = {
    new SendBeforeImageForUpdatesTrait(emitUpdateBefore)
  }
  val DEFAULT = new SendBeforeImageForUpdatesTrait(false)
}